# @import ./_shared_variables.http
###
# Load MapGuide Package file
# @name load_package

POST {{endpoint_base}}
Content-Type: multipart/form-data; boundary={{boundary_marker}}

--{{boundary_marker}}
Content-Disposition: form-data; name="USERNAME"

{{admin_user}}
--{{boundary_marker}}
Content-Disposition: form-data; name="PASSWORD"

{{admin_pass}}
--{{boundary_marker}}
Content-Disposition: form-data; name="OPERATION"

APPLYRESOURCEPACKAGE
--{{boundary_marker}}
Content-Disposition: form-data; name="VERSION"

1.0.0
--{{boundary_marker}}
Content-Disposition: form-data; name="LOCALE"

{{locale}}
--{{boundary_marker}}
Content-Disposition: form-data; name="CLIENTAGENT"

{{agent}}
--{{boundary_marker}}
Content-Disposition: form-data; name="MAX_FILE_SIZE"

100000000
--{{boundary_marker}}
Content-Disposition: form-data; name="PACKAGE"; filename="Sheboygan.mgp"

< ./data/Sheboygan.mgp
--{{boundary_marker}}--

?? status == 200
###
# Create Session
# @name create_session
# @ref load_package

POST {{endpoint_base}}
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

USERNAME={{admin_user}}&PASSWORD={{admin_pass}}&OPERATION=CREATESESSION&VERSION=1.0.0&LOCALE={{locale}}&CLIENTAGENT={{agent}}

?? status == 200
?? header content-type includes text/plain

@session = {{create_session}}