@endpoint_domain = http://localhost:8008
@endpoint_base = {{endpoint_domain}}/mapguide/mapagent/mapagent.fcgi
@admin_user = Administrator
@admin_pass = admin
@locale = en
@agent = MapGuide Integration Test Suite
@boundary_marker = WebKitFormBoundary
@format_xml = text/xml
@format_json = application/json