# Build thirpdarty
RUN THIRDPARTY_BUILD_DIR=/usr/local/src/fdo/build_thirdparty \
&& ccache -s \
&& cd /usr/local/src/fdo/ \
&& ./cmake_bootstrap.sh --working-dir $THIRDPARTY_BUILD_DIR --all-internal --build 64 \
&& ccache -s

# Main build
RUN THIRDPARTY_BUILD_DIR=/usr/local/src/fdo/build_thirdparty \
&& ccache -s \
&& BUILD_DIR=/usr/local/src/fdo/build \
&& mkdir -p $BUILD_DIR/artifacts \ 
&& cd /usr/local/src/fdo/ \
&& ./cmake_build.sh --fdo-ver-major __FDO_VER_MAJOR__ --fdo-ver-minor __FDO_VER_MINOR__ --fdo-ver-rel __FDO_VER_REL__ --fdo-ver-rev __FDO_VER_REV__ --build 64 --thirdparty-working-dir $THIRDPARTY_BUILD_DIR --cmake-build-dir $BUILD_DIR \
--with-sdf --with-shp --with-sqlite --with-ogr --with-gdal --with-wfs --with-wms --with-genericrdbms --ninja \
&& ccache -s \
&& cd $BUILD_DIR \
&& cmake --build . --target package \
&& mv fdosdk*.tar.gz $BUILD_DIR/artifacts